name: Plugin Tests
# Run on every push, and allow it to be run manually.
on:
  workflow_dispatch:
  push:
    branches: ['main', 'v*']
  pull_request:

env:
  VSIGN_URL: ${{ secrets.TPP_URL }}
  VSIGN_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  plugin-tests:
    # Skip if running in a fork that might not have secrets configured.
    if: ${{ github.repository == 'venafi/csm-opa-plugin' }}
    name: Run tests
    runs-on: ubuntu-latest
   
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-go@v3.3.0
        with:
          go-version: '1.23.6'
          check-latest: true
      - name: build cms-opa-plugin
        run: |
          make build
          echo "$PWD" >> $GITHUB_PATH
      - name: Sign with opa plugin
        run: |
          echo "Sign with RSA certificate"
          ./bin/opa build --bundle ./policy --output ./policy/bundle.tar.gz --signing-key vsign\\rsa2048-cert --signing-plugin csm-opa-plugin
          ./bin/opa sign --bundle --signing-key vsign\\rsa2048-cert --signing-plugin csm-opa-plugin ./policy
          echo "Sign with ECDSA certificate"
          ./bin/opa sign --bundle --signing-key vsign\\p256-cert --signing-plugin csm-opa-plugin ./policy

